spring:
  datasource:
    url: jdbc:mysql://localhost:3306/passbook?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: 123456
#    driverclass-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
          ##配置卡夫卡的 位置
  kafka:
    bootstrap-servers: 127.0.0.1:9092
    ##配置消费者组所在的id
    consumer:
      group-id: psaabook
      ##配置4个线程去监听监听 topic
    listener:
      concurrency: 4
server:
  port: 9527
logging:
  level:
    com.hjx.passbook: debug
  ##在当前工程自动生成文件 存储log
  file: hjx-merchants.log




